services:
  - type: web
    name: cardapio-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run db:migrate && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_AUTH_TOKEN
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false

